dist: bionic
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
  - touch filesystem
  - truncate filesystem --size 1000000
  - ./miniFS filesystem init <../test/test_input.txt | cmp ../test/test_output.txt

notifications:
  email:
    recipients:
      - grib.a@phystech.edu
    on_success: change
    on_failure: always
